### ISSUE TITLE
trajectory plan(s)

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/the-oregon-trajectory#11]
we need to figure out:

1. how trajectory choosing works

and assuming we go with the 'select one trajectory at start' way

2. what is the primary trajectory?

**Comment by MrNubbin** [comment]
From what I understand is that we want to get to an asteroid? The truth is there are asteroids EVERYWHERE in the solar system (not just the asteroid belt and Kuiper belt). They're flying by Earth all the time. Actually, that's the kind of asteroid that the Asteroid Redirect Mission (ARM) is going to fly to but this project is the FUTURE history catalyzed by that historic mission to be. So how about we look at the Kuiper Belt and colonize Pluto or something? The New Horizons will have flown by Pluto before then and maybe, just maybe we could have found something interesting... *insert twilight zone intro* We need to make sure we throw a lot of kudos at ARM (and not New Horizons) and its contributions to this future (since that's part of the challenge), the judges will like that too.

Unlike a near Earth object like what ARM will fly to, the Kuiper Belt is WAY out there and will require more fly-bys (and by "more" I mean any fly-by's period) which makes for a fun game! For reference, the trajectory depends on what kind of engine you use. There are three options I think we could play with for this game: Chemical, electric (ion/plasma), or solar sail. Essentially the Chemical engine will be the most expensive eating up a lot of your initial cash (now like $800 million instead of $800.00), the electric engine is medium, and the solar sail is interplanetary trajectories on a budget.

The Chemical engine will have a more direct path and a shorter mission duration. Maybe like Lunar->Jupiter->Saturn/Uranus/Neptune maybe even see a moon or two of the gas giants. The electric engine take a while to spool up and get up to speed so it'll have a more scenic route flying by Earth->Mars->Jupiter->Saturn/Uranus/Neptune and probably also seeing some asteroids in the... well... asteroid belt. The solar sail will actually be between the chemical and electric in duration, but will have to fly a lot closer to the Sun. It will have to fly into the solar system by doing something like Lunar->Venus->Mercury and then unfurl its sails close to the Sun and shoot out towards Jupiter/Saturn/Uranus/Neptune for other fly-bys (that's going to be fun to plan...)

I think for v1.0.0 we should just focus on the engine-specific trajectories and not necessarily multiple trajectories for each engine. Regardless, I can (hopefully) whip up some nice trajectories without fibbing too much and get you a screenshot of the path. The software I use isn't made to be pretty, but I can hand it off as kind of a blue print for our designers.

**Comment by 7yl4r** [comment]
This is beautiful. Everything I was hoping for and more. Let's build this out 1 trajectory at a time, and since Chemical rockets are those people are most familiar with, let's start there (unless you like another one better). Let's pick particularly scenic or scientifically interesting points near to the trajectory and perhaps give a $ bonus for collecting science or something like that to explain why we're going a little out of the way.

So, to start off a listing of the "locations" Oregon-trail style is:

"Towns" in order:

* Earth
* Moon
* one of the main belt asteroids
* Jupiter
* Saturn
* pluto

Engine-driven Maneuver Nodes (aka rivers)

* Earth/Moon transfer orbit

Gravity assist maneuvers
* Moon gravity assist
* Jupiter grav assist
* Saturn grav assist
* Uranus grav assist

Unique locations
* Launch
* destination

I think it would be nice to work a Lagrange point in there somewhere primarily for teaching value. Where should that go? Also, I don't know which moons would make the most sense and be most interesting. Let's give this one more pass so we can give the artists/writers/sound designers something to go off of.

**Comment by MrNubbin** [comment]
Oh yeah chemical is the easiest for sure and I can get a good baseline form that. We can add some other actual "towns" like a base on Jupiter's more popular moons Europa and/or Ganymede, on Saturn's most popular moon Titan, Neptune's most popular moon Triton, or Uranus' Oberon and/or Titania. We can also put a space station at some planet's (or multiple planets) Lagrange point as another town. Perhaps before every flyby the player can choose whether to stay at the space station at the lagrange point or continue on ahead with the maneuver? With actual towns the player can actually benefit from $ from science/rare mineral collection bonuses.

I'm also sure we could just happen to fly by Vesta, Ceres, or like Halley's comet. (Let's use some hand waiving and just say we pass them by for my sake)

**Comment by 7yl4r** [comment]
What do you think are the top 10 destinations we can implement first?

**Comment by MrNubbin** [comment]
Earth, Moon, Mars, Europa station (instead of Jupiter), Titan station (instead of Saturn), Uranus, Neptune, Pluto for sure. That leaves two for Ceres and Halley's Comet? Although Halley's Comet would just be for show. I'll see if I can get something by Sunday.

**Comment by terpin** [comment]
It would be really cool to just draw the background for a comet where the
tail stretches out behind it while you pass it by!

**Comment by 7yl4r** [comment]
I think we ought to move all this great info over to the wiki. Let's focus on the one chemical rocket trajectory, but leave stubs to expound on the others later.

**Comment by MrNubbin** [comment]
After work I'll get this info to the wiki as well as outline future work.

**Comment by 7yl4r** [comment]
trajectory up on the wiki
