### ISSUE TITLE
listing of existing & needed sound assets 

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/the-oregon-trajectory#17]
Maybe we ought to set up a wiki page showing what sound assets we have to work with, along with a list of what we want. Then we can start matching up the two. Maybe also a bit of discussion on the style of the sounds and music too.

**Comment by jharrisonmusic** [comment]
Yeah a wiki would be great, a list would be fantastic for me to just go down and create a few versions of each so there can be variety.

My rough list so far looks like:
Rocket sounds
An enter confirmation sound

Musical queues for:
Something good
Something bad
Something neutral
Losing
Winning
Title scene theme
Atmospheric music (perhaps several different iterations to be introduced in different environments or in different situations)

I need to read through more of the story so I can create some plot tree specific sounds, but this is my first set of goals.  Are there any major areas that I'm missing or that people would like to see specific sound/music developed for?

**Comment by 7yl4r** [comment]
This looks like a great starter list. I've put it up on the wiki [here](https://github.com/7yl4r/the-oregon-trajectory/wiki/sound-design), and you should be edit it directly. Once we have some files put them in the `/assets/sounds/` directory and then we'll start working them into the game.

I once saw some cool "real" space sounds recorded from various frequencies and transposed to human hearing range. It might be cool to work those in somewhere and then pop up a link to the science article.

I can't think of any other sounds we'll need though, maybe @MrNubbin (hereforth christened space-science pope) has some ideas for interesting space sounds? I mean... technically there's no sound in a vacuum, but the ship hulls are supposed to be pretty creaky, right? =P

**Comment by MrNubbin** [comment]
You pretty much nailed it. Just some suggestions on specifics:
  
Atmospheric music: When I think of atmospheric music I think of [Space Mountain](https://www.youtube.com/watch?v=azxQYf9KT94) at Disney. A lot of whoops and chimes (for lack of better words). I'd even be ok with the intro. And yes I'm now listening to that the whole time I'm typing this.
  
Maybe add some incoherent radio chatter randomly? Essentially you can tell people are talking but no specifics of what theyre saying. You know, like when they're deep throating the mic and yelling at a [drive through](https://www.youtube.com/watch?v=Jv6lmtVDxzo) . Sprinkle in random "Houston", "Roger", "Affirmative", etc. and hopefully not yelling.
  
Oh and maybe sprinkle in some random sci-fi [beeps and boops](https://www.youtube.com/watch?v=lPFKd5p_t0s). Everyone loves beeps and boops. I'd like to hear other random sound effects going on too instead of just the atmostpheric music. Creaky spaceship would be good too. These are just ideas, take em or leave em. You're the expert!
  
Your Spaciousness,
Space-Science Pope

**Comment by 7yl4r** [comment]
wow. the motherload: https://soundcloud.com/nasa

**Comment by 7yl4r** [comment]
these sounds are awesome. I've got a few more ideas for optional assets I'm adding to the wiki now.
