### ISSUE TITLE
sprites for the travelling screen

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/the-oregon-trajectory#18]
An animated ship is the obvious first one. I think the original had different sprites for the wagon & oxen, and we might want to consider a "modular ship" as well, but that's contingent on the game options I suppose. I think the rocket you have now will do for now.

We also want a sprite that will mark a "maneuver node" where a player needs to perform an orbital transfer. These are analogous to the rivers in Oregon Trail. 

Lastly, though the backgrounds might mark locations, I think we also want some sprites to represent a station, ship, landmark, or other structure that the player will come upon. (towns/landmarks in Oregon trail). We've got some creative freedom on what these should be, and I'm sure @MrNubbin has ideas.

**Comment by MrNubbin** [comment]
You bet I do! We need to come up with themes for each town. A balance between silly but informative could be good. Like the people on Titan (Saturn's moon) are all hula hooping or just have big hoop skirt outfits (because Saturn's rings) or everyone is sideways on the screen at Uranus because the planet's axis is tilted at 97 deg. I'm sure we can get more creative but that's just a start.

Once we have themes I think we'll have good ideas for the what the towns will look like.

**Comment by JrodManU** [comment]
Here's some module ideas: Extra engine (Speed), heat-tech plating (happiness?), and extra food (health)

**Comment by 7yl4r** [comment]
Sweet. I think it makes sense to keep these in /assets/sprites/ and we'll start pulling them into the code when we get there.

**Comment by JrodManU** [comment]
Didn't realize we have a folder; I'll put stuff in there when I make it
