### ISSUE TITLE
writing for random events/encounters

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/the-oregon-trajectory#61]
text surrounding the random events/encounters is needed. Imagine what the player should see & read for each event. What should the outcome be (loss of health, gain of food, etc). What kind of sprite should we use for this event?

The more of these we have, the more organic (and fun) the game will feel. There are some ideas [over on the wiki](https://github.com/7yl4r/the-oregon-trajectory/wiki/random-events), but these need to be developed a lot more.

**Comment by 7yl4r** [comment]
[Just posted to /r/writingprompts](http://www.reddit.com/r/WritingPrompts/comments/323zee/wp_it_is_2055_and_your_spaceship/) in hopes of getting something.

**Comment by terpin** [comment]
I can help come up with some stuff, I just have to finish a few writing
assignments today.

How long should the encounter be (like a few paragraphs? should there be
multiple outcomes, depending on how they handle the situation?

**Comment by 7yl4r** [comment]
They can be as long or as short as you want. We can do multiple outcomes (the debris encounter has some). Just make some quick notes about how you want it to work and we'll do our best to make the code do it. 

I'll write up a bit more on the debris encounter in a few minutes to demonstrate.

**Comment by 7yl4r** [comment]
[there we go](https://github.com/7yl4r/the-oregon-trajectory/wiki/random-events#space-debris-encounter)

**Comment by terpin** [comment]
Thanks, how many of these do you think we'll need?

**Comment by 7yl4r** [comment]
We only need a couple, but I think more variation will make it more fun. Maybe we should have multiple different texts for the same scenario. That is pretty easy to set up in the code, we just need the writing.

**Comment by terpin** [comment]
Encounter 1: “Phantom Signal”

As you speed towards your next destination, your radio picks up a faint
rhythmic clicking.

Your radio could just be picking up low level cosmic background radiation,
but there’s a small chance that the signal could be coming from another
ship or a cache of supplies.


/


During a routine maintenance stop, your crew notices a distant radio
signal. It’s possible it’s just microwaves or cosmic background radiation,
but it also could be something else - like a great opportunity to trade!


Do you:


(Option 1) Investigate the signal.

(Outcome 1) It wasn’t background radiation at all – it’s a small ship.
They’ve been trying to signal for help for almost a week. They give you all
X food and X fuel in exchange for a ride to the next station.

(Outcome 2) It was just background radiation, and you lost x fuel

(Outcome 3) You found a ship, but it appears to have been abandoned long
ago. You salvage x scrap, x fuel and x food.


(Option 2) Change course to avoid the signal?

(Outcome 1) You lose x fuel changing course, but steer clear of the signal.

(Outcome 2) You lose x fuel changing course. While you could have used more
supplies, the risk to the mission wasn’t worth it.


(Option 3) Ignore the signal and continue on your current path?

(Outcome 1) You decide to continue on your way without investigating the
signal, but you always wonder what was out there.

(Outcome 2) You and your crew decide that it’s not worth the risk checking
out the signal and continue on your way.

**Comment by 7yl4r** [comment]
Very nice. I like the format as well.

**Comment by terpin** [comment]
Encounter 2 “Repairs”


Your ship has taken a beating during the course of your journey, and you’ve
come to a full stop off the trajectory to do some quick repairs that should
hold until you get to your next destination.


*pop* *pop* *ping*


At first everyone inside the ship panics, worrying that the hull has begun
to buckle – but you breathe a sigh of relief when you realize it’s just a
tether coming loose… Wait.


A safety tether? Like the one the crew uses to stay attached to the ship
outside during repairs!

Astronauts have a SAFER (Simplified Aid for EVA Rescue) device built into
their suits to help them stay close to the ship if a tether breaks, but
you’ll have to be very careful about how you proceed to recapture your
free-floating crew.



/


You’ve come to a full stop after one of your repair teams noticed a weak
spot your hull during an EVA (Extravehicular Activity) walk. While the
repair team does its work, the rest of the crew takes some much needed time
to rest, relax and share memories of home none of you may never see again.

*craaaaaaaaaaaaaaaack*


All of a sudden a loud crack comes from the outer hull. Everyone panics,
worrying that it may be that weak spot in the hull giving way… but nothing
happens.


Moments later you hear a call for help coming from the radio – your repair
crew somehow came untethered from the hull and need help getting back to
the ship. The SAFER (Simplified Aid for EVA Rescue) devices in their EVA
suits will keep them close to the ship, but they may not be able to all
make it back on their own.


What do you do?


(Option 1) “You can’t put a cost on human lives, we’ll do anything to save
our crew!” Rescuing the crew will cost x fuel and x food.


(Outcome 1) You successfully rescued all of your crew, but you lost x fuel
and x food in the process.


(Outcome 2) You successfully rescued all of your crew, and luckily didn’t
waste any fuel or food


(Outcome 3) You were able to rescue some of your crew, but %random name%
didn’t make it. Your crew continues on their journey, and will always
remember %random name%’s selfless sacrifice.


(Option 2) “It’s too risky, we have to put the safety of the mission first.
They’ll have to try and get back to the ship on their own.”


(Outcome 1) Your repair crew was able to maneuver themselves back to the
ship and get back to safety. They were lucky, this time. You continue on
your journey.


(Outcome 2) Some of your repair crew made it back to the ship, but only
because %random name% used their remaining thrusters to push everyone back
to the ship. Everyone will always remember %random name%’s bravery, and you
continue on your journey.


(Outcome 3) Your stranded crew members were unable to get back to the ship
in time, and have sunk into the inky blackness of space. The crew mourns
this terrible loss, and you quietly resume your journey. You ask yourself
if you could have done something differently.

**Comment by MrNubbin** [comment]
I like everything on the repair event except the "come to a full stop" part. We need a whole launch vehicle to even go that fast, you wouldn't just stop (I know there's a balance between realism and making this game fun so i will concede if thats the case).

My suggestion for why there is hull damage is micrometeroids.

**Comment by terpin** [comment]
Encounter 3 “The Experiment” (common)


You and your crew are running an important experiment that will take
another 5 hours to complete, but you’ve received a space weather report
warning of an impending proton storm. Proton storms, also known as “solar
particle events”, happen when particles emitted by the sun during coronal
mass ejects and solar flares are pushed out into space.


Luckily your spacecraft is equipped with a shielded pod that will protect
you from the storm – but your crew isn’t the only thing you have to worry
about! Energized protons can damage electronic components, cause software
contamination and can even result in unexpected (sometimes called
“phantom”) spacecraft commands to be executed.


It’s probably a smart idea to turn off your equipment and stop your
experiment until after the storm passes in a few hours, but your chief
science officer believes that you’re on the edge of a breakthrough. What do
you do?


Option 1 Stop the experiment, you can always try again later.


(Outcome 1) You and your crew emerge from the shielded pod safe and sound.
You try to rerun your experiment, but fail because you only had enough
materials to run the experiment once, and have to chalk this one up to
experience. Better luck next time!


(Outcome 2) The solar storm lasted for only an hour, and all of your crew
emerges from the shielded pod ready to resume the experiment. Your
equipment suffered no damage and your experiment was successful!


(Outcome 3) The solar storm lasted a lot longer than expected, and your
crew needs to rest for a while before they resume the experiment. The
conditions needed to test your experiment no longer exist, and you’ll have
to try again later.



Option 2 “This experiment is too important to stop! We’ll just have to hope
the rewards outweigh the risk…”


(Outcome 1) You and your crew emerge from the shielded pod many hours
later, long after your experiment should have been finished. Amazingly
enough you didn’t lose any data and your equipment is undamaged – and
you’ve made an amazing new discovery about proton storms, too!


(Outcome 2) The proton storm lasted many hours, and when you and your crew
emerge from the pod you find a good deal of your equipment ruined along
with the results of your experiment. Better luck next time!


(Outcome 3) The proton storm wasn’t nearly as bad as predicted and is over
in 45 minutes. You and your crew emerge safely from the pod, only to find
your equipment malfunctioned and ruined your experiment. You’ll have to
wait several weeks before conditions are favorable again.

**Comment by terpin** [comment]
Encounter 4 “Space Medicine” (common)


As you speed along towards your next destination you come across a science
ship investigating the effects of long term spaceflight on human health,
and they’d like to examine your crew!


After almost a century of humans traveling in space (it *is* the 2050s,
anyway!), the ill-effects of space travel on human health have been well
documented. Many of the technological advances that we enjoy in medicine
came out of the space program (lightweight wheelchairs, CAT and MRI scans,
implantable pacemakers, and radiation therapy, to name a few!


The research collected by this team could help future colonists and even
people back home on Earth – but it will cost x fuel and x food to
participate in the study.


Option 1 “We should do what we can to help, right?”


(Outcome 1) The team from the other ship studies your crew and gains new
insight into the effects of long term spaceflight on human health. They
give you x fuel and x food as a reward for helping them further their
knowledge.


(Outcome 2) The team from the other ship studies your crew, but sadly they
learn nothing new. You lost x food and x fuel participating in the study.


(Outcome 3) The team from the other ship comes aboard and studies your
crew’s behavior and health for a short period of time – and they discover a
way to combat blindness and bone loss, two of the most common effects of
space travel.


Option 2 “We don’t have time to participate in a study, the mission is more
important.”


(Outcome 1) You decided not to participate in the study. You leave the ship
behind you, knowing that there will be many other volunteers following in
your footsteps in the coming months.

**Comment by 7yl4r** [comment]
implemented
